V-01/F-01 task complete
Maksim2103/gh-pages-start pull request #1
Opened 2021-09-18 14:29 UTC by Maksim2103

надеюсь правильно оформил)

2021-09-20 14:48 UTC, EvgeniyaFilatova requested changes

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on package.json
> +    "swiper": "^7.0.6",
А зачем в проекте swiper? Вроде нигде не используется. На будущее?

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/App.js
> +        <div className="content">
- [ ] И content-wrapper, и content лучше убрать в компонент Content - это ведь непосредственно к этому компоненту и относится

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/App.js
> +      <div className="side-bar">
- [ ] Лучше убрать этот div в компонент SideBar, так как относится именно к этому компоненту данный div

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/App.js
> +        <div className="slider">
- [ ] Здесь то же самое

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/Content/FooterContent/index.jsx
> +    <div className="footer-content-wrapper">
- [ ] А почему здесь wrapper не сделал элементом блока footer-content (по БЭМ)? Вроде у тебя в остальных компонентах это именно как элемент идет (например, header-content__wrapper). Сделай здесь тоже __wrapper

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/MainButton/index.jsx
> +      style={{
- [ ] Не очень хорошо делать инлайновые стили, потом их нельзя из css перекрыть. Лучше здесь сделать через модификаторы (ты как раз используешь БЭМ) - то есть передавать в компонент свойство, в зависимости от которого будешь добавлять в className определенный класс с модификатором (например, main-button--green). Для компановки className можешь использовать пакет "classnames". С размерами кнопки тоже попробуй сделать по аналогии, у тебя по проекту в принципе не так много различных размеров кнопок встречаться будет, под них тоже можно сделать модификаторы

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/SideBar/BurgerMenu/index.jsx
> +              </svg>{' '}
- [ ] Убрать {' '} после </svg>

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/Slider/index.js
> +    title: 'Бесплатный парковка',
- [ ] Исправить грамматическую ошибку

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/MainButton/index.jsx
> +        {buttonText}
- [ ] На кнопках не тот шрифт, нужно прописать тот, что по фигме
- [ ] Поведение кнопок привести в соответствии с гайдлайном (страница в фигме 0. Guideline), там вроде просто цвет шрифта не тот у тебя

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/components/Slider/index.js
> +      <AwesomeSlider animation="cubeAnimation">
- [ ] Цвет стрелок на слайдере не тот, что на фигме

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/App.scss
> +}
- [ ] У тебя получается уже очень большой файл со стилями, дальше будет ещё больше. И плюс у тебя очень большая вложенность, обычно не рекомендуется делать вложенность больше 3. Поэтому предлагаю тебе попробовать разбить твой большой файл со стилями на отдельный файлы под каждый компонент. Так они будут компактнее и каждый компонент у тебя будет самостоятельным. Используй, например, css модули для этой цели

2021-09-20 14:48 UTC, EvgeniyaFilatova commented on src/App.scss
> +  cursor: url('./assets//images/Cursor.png'), auto;
- [x] Курсор не нужно кастомизировать под тот, что в фигме
![image](https://user-images.githubusercontent.com/90593835/134022249-1a450438-0bf6-46c7-9c31-ba1456c8cd7d.png)

2021-09-20 15:12 UTC, EvgeniyaFilatova commented on src/App.scss
> +  font-family: light;
- [ ] Лучше дать более осмысленные названия для шрифтов. И кстати можно шрифты с разным начертанием подключать с одинаковым названием, просто прописывать для каждого свойство font-weight

2021-09-21 18:36 UTC, Maksim2103 commented on package.json
> +    "swiper": "^7.0.6",
Удалил. Я сначала его хотел просто использовать, а потом передумал)

2021-09-21 18:39 UTC, Maksim2103 commented on src/App.js
> +        <div className="content">
Исправил content-wrapper на Container, так как он нужен мне здесь для flex. А Content убрал

2021-09-21 18:39 UTC, Maksim2103 commented on src/App.js
> +      <div className="side-bar">
убрал

2021-09-21 18:39 UTC, Maksim2103 commented on src/App.js
> +        <div className="slider">
тоже убрал)

2021-09-21 18:40 UTC, Maksim2103 commented on src/components/Content/FooterContent/index.jsx
> +    <div className="footer-content-wrapper">
Поменял название с использование модулей

2021-09-21 18:41 UTC, Maksim2103 commented on src/components/Slider/index.js
> +    title: 'Бесплатный парковка',
Исправил, копипаст не всегда хорошо,)

2021-09-21 18:41 UTC, Maksim2103 commented on src/components/MainButton/index.jsx
> +        {buttonText}
Поправил кнопку и ее поведение

2021-09-21 18:42 UTC, Maksim2103 commented on src/components/Slider/index.js
> +      <AwesomeSlider animation="cubeAnimation">
уже тот)

2021-09-21 18:43 UTC, Maksim2103 commented on src/App.scss
> +}
Файл разбил, модули подключил. Вроде даже ничего не сломал и все работает)

2021-09-21 18:44 UTC, Maksim2103 commented on src/App.scss
> +  cursor: url('./assets//images/Cursor.png'), auto;
вернул кастомизацию на место)

2021-09-21 18:44 UTC, Maksim2103 commented on src/App.scss
> +  font-family: light;
Задал название и прописал font-weight

2021-09-21 18:46 UTC, Maksim2103 commented on src/components/MainButton/index.jsx
> +      style={{
Применил пакет 'Classname', модифицировал кнопки и заодно слайдеры)

2021-09-21 18:47 UTC, Maksim2103 commented on src/components/SideBar/BurgerMenu/index.jsx
> +              </svg>{' '}
это было самое легкое)

2021-09-22 05:26 UTC, EvgeniyaFilatova requested changes

2021-09-22 05:26 UTC, EvgeniyaFilatova commented on src/components/MainButton/mainButton.module.scss
> +  text-transform: uppercase;
- [ ] Здесь не нужен text-transform по макету

2021-09-22 05:26 UTC, EvgeniyaFilatova commented on src/components/MainButton/index.jsx
> +let cx = classNames.bind(styles);
- [ ] Здесь нет необходимости в let, лучше использовать const

2021-09-22 05:26 UTC, EvgeniyaFilatova commented on src/components/Slider/SliderItem/index.jsx
> +let cx = classNames.bind(styles);
- [ ] То же самое, заменить на const

2021-09-22 05:30 UTC, EvgeniyaFilatova commented on src/App.scss
> +@font-face {
- [ ] Тебе нужно подключить все шрифты с различным начертанием через @font-face, вот по типу такого:
![image](https://user-images.githubusercontent.com/90593835/134288228-dcbf8319-5a16-474e-808c-963f57470016.png)

2021-09-23 17:29 UTC, merged