V-06 task comleted
Maksim2103/gh-pages-start pull request #13
Opened 2021-10-06 07:53 UTC by Maksim2103

2021-10-07 06:08 UTC, EvgeniyaFilatova commented
- [ ] Блок с изображением должен быть чуть ниже, верхняя граница на уровне заголовка "Ваш заказ подтвержден"
![image](https://user-images.githubusercontent.com/90593835/136328958-71dcdd84-8355-4570-9791-0a065af4183d.png)

2021-10-07 06:09 UTC, EvgeniyaFilatova commented
- [ ] На кнопке должна быть надпись "Отменить"
![image](https://user-images.githubusercontent.com/90593835/136329116-74612f72-eab1-436f-8430-e2b0688162e0.png)

2021-10-07 06:12 UTC, EvgeniyaFilatova commented
- [ ] Снова разные отступы у блоков, ориентируйся всегда на шапку сайта. Вообще лучше сделать один враппер для всех, чтобы ты не страдал
- [ ] Сделай отступ между изображением и "Ваш заказ" побольше
![image](https://user-images.githubusercontent.com/90593835/136329412-127b4fb9-01af-4d70-8d75-2a2f00a1f906.png)

2021-10-07 06:17 UTC, EvgeniyaFilatova commented
- [x] Отступ снизу кнопки нужно добавить
![image](https://user-images.githubusercontent.com/90593835/136329859-ccaa5068-af9d-4e11-9f07-2a666611d5e8.png)

2021-10-07 06:21 UTC, EvgeniyaFilatova requested changes

2021-10-07 06:21 UTC, EvgeniyaFilatova commented on src/redux/orderSlice.js
> +    isBreadCrumbs: true,
- [ ] Ты хранишь в редаксе отображение хлебных крошек? В редаксе хранят бизнес данные чисто. Для таких вещей, как отображение элементов, используют обычный стейт компонента. Убери хлебные крошки из редакса, перенеси в стейт компонента

2021-11-11 09:00 UTC, chugunovns21 requested changes

2021-11-11 09:00 UTC, chugunovns21 commented on src/components/Pages/OrderPage/OrderConditions/index.jsx
> +  };
Если в этой функции не используется ничего, из внутреннего стейта компонента, то ее можно засунуть в пропсы как колбек и сразу передать в onClick, без этой обертки.

2021-11-11 09:00 UTC, chugunovns21 commented on src/components/Pages/OrderPage/OrderContainer/index.jsx
> +  console.log('isBreadCrumbs', isBreadCrumbs);
Консоль нужно чистить перед мержем

2021-11-11 09:00 UTC, chugunovns21 commented on src/components/Pages/OrderPage/OrderOptions/index.jsx
>    return (
Так как компонент у нас только возвращает верстку, мы можем использовать синтаксис стрелочных функций, и обходится без return. Тут, наверное, уже не надо исправлять, но в дальнейшем следи за этим))

2021-11-12 07:10 UTC, merged