F 03/ F-04
Maksim2103/gh-pages-start pull request #18
Opened 2021-11-18 09:58 UTC by Maksim2103

2021-11-18 16:24 UTC, chugunovns21 commented
Раз уж мы начали твой путь самурая, то давай продолжим:
Выглядит не красиво, давай не отображать этот блок, если нет никакой информации в заказе
![image](https://user-images.githubusercontent.com/63374297/142455036-09b0eee2-15eb-4ad9-9ecb-a32a970f1e3b.png)

2021-11-18 16:25 UTC, chugunovns21 commented
Тут все еще нет курсор:поинтер
![image](https://user-images.githubusercontent.com/63374297/142455231-df10b6cd-c4e8-4fe4-98f6-219ec680d323.png)

2021-11-18 16:26 UTC, chugunovns21 commented
Блок не прокручивается, не возможно посмотреть все машины
![image](https://user-images.githubusercontent.com/63374297/142455439-0d6edc67-8a26-4c0c-9d76-846c4e31f65c.png)

2021-11-18 16:30 UTC, chugunovns21 commented
Оформи это красивее
![image](https://user-images.githubusercontent.com/63374297/142455766-dc46826c-810d-44dc-941e-0afe04cea866.png)

2021-11-18 16:31 UTC, chugunovns21 commented
Серьезная ошибка: данные по машинам нужно получать один раз, а не запрашивать каждый раз при включении вкладки

2021-11-18 16:32 UTC, chugunovns21 commented
Хедер уехал
![image](https://user-images.githubusercontent.com/63374297/142456534-0ce120ca-99ca-452e-9552-4b993c11a57d.png)

2021-11-18 16:35 UTC, chugunovns21 commented
Вот этот блок должен быть фиксированный
![image](https://user-images.githubusercontent.com/63374297/142457071-d0399c05-c36f-486b-bf51-e3619fdf046c.png)

2021-11-19 17:51 UTC, chugunovns21 commented
Текст в кнопке меняет цвет при ховере 
![image](https://user-images.githubusercontent.com/63374297/142668648-f7f91c16-db34-4c57-bddb-7ab0d180b854.png)

2021-11-19 17:55 UTC, chugunovns21 commented
Нет справа бордера у карточек, двойной скрол
![image](https://user-images.githubusercontent.com/63374297/142669169-5722dcb8-ec8b-40d8-86f1-d5b89a7c3a10.png)

2021-11-19 17:56 UTC, chugunovns21 commented
На мобильном карточка выделяется серым
![image](https://user-images.githubusercontent.com/63374297/142669309-7fb53aba-778c-478b-a4e5-6225bae5f1a1.png)

2021-11-23 09:30 UTC, EvgeniyaFilatova commented
- [ ] Картинки искажаются, исправь. Можно использовать свойство object-fit
![image](https://user-images.githubusercontent.com/90593835/142999845-b51ee7e6-0e06-41b1-98a2-3dac9eca308e.png)

2021-11-23 09:32 UTC, EvgeniyaFilatova commented
- [ ] Проверь что тут с блоком, у меня в одном браузере скролл заезжает за окно, в другом обрезаются блоки с машинами
![image](https://user-images.githubusercontent.com/90593835/143000265-4f0780af-e0a0-45af-b245-a39ed0a74f9f.png)
![image](https://user-images.githubusercontent.com/90593835/143000341-d5ee5b93-5292-4024-974f-d3df10e81f74.png)

2021-11-23 09:47 UTC, EvgeniyaFilatova requested changes

2021-11-23 09:47 UTC, EvgeniyaFilatova commented on src/components/Pages/OrderPage/OrderModel/ModelSelect/index.jsx
> +          checked={value === '' ? true : false}
- [ ] Используй логическое преобразование типов

2021-11-23 09:47 UTC, EvgeniyaFilatova commented on src/components/Pages/OrderPage/OrderConditionsMobile/index.jsx
> +import React from 'react';
- [ ] А зачем сделал отдельный компонент под мобильную версию? Всё должно быть сделано в рамках одного компонента: и десктоп, и мобильная версия. Плюс я смотрю ты на втором шаге решил сделать модальное окно для вывода деталей заказа - нехорошо, когда разметка от страницы к странице меняется, нужно сделать в одном стиле

2021-11-23 09:47 UTC, EvgeniyaFilatova commented
- [ ] Кнопка перехода на следующий шаг доступна даже если не была выбрана модель машины. Должна быть недоступна
![image](https://user-images.githubusercontent.com/90593835/143002364-7312f0d8-6d0d-4ffa-b85a-7d3841f901e9.png)

2021-11-23 09:50 UTC, EvgeniyaFilatova commented
- [ ] Пропиши для данного блока стиль с псевдоклассом :active и добавь там зеленую рамку
![image](https://user-images.githubusercontent.com/90593835/143002723-dad45001-8292-4531-bd2f-36c76a653f66.png)

2021-11-23 11:37 UTC, EvgeniyaFilatova commented on src/components/Pages/OrderPage/OrderModel/ModelSelect/index.jsx
> +          checked={value === ''}
Можно написать !!value

2021-11-23 11:39 UTC, merged